add ciad, jpegoptim, zquote

diff --git a/tldr/bin/tldr b/tldr/bin/tldr
--- a/tldr/bin/tldr
+++ b/tldr/bin/tldr
@@ -1,30 +1,34 @@
-#!/bin/bash
+#!/bin/sh
 # tldr client by Ray Lee, http://github.com/raylee/tldr
 # a Sunday afternoon's project, I'm sure there's room for improvement. PRs welcome!
 
-set -uf -o pipefail
+set -uf
+# next only works on some shells, check for support before trying to set the feature
+set -o | grep -q pipefail && set -o pipefail 2>/dev/null
 
 # initialize globals, sanity check the environment, etc.
 config() {
     init_term_cmds
 
-    if [ -z $(which curl) ]; then
-        echo "${red}tldr requires \`curl\` installed in your path$reset"
+    if [ -z "$(command -v curl)" ]; then
+        echo "${red}tldr requires \`curl\` installed in your path${reset}"
         exit 1
     fi
-
     configdir=~/.tldr
     [ -d ~/.config ] && configdir=~/.config/tldr
 
     platform=$(get_platform)
     base_url="https://raw.githubusercontent.com/tldr-pages/tldr/master/pages"
-    index_url="http://tldr-pages.github.io/assets/index.json"
+    index_url="https://raw.githubusercontent.com/tldr-pages/tldr-pages.github.io/master/assets/index.json"
     index="$configdir/index.json"
     cache_days=14
     force_update=''
 
     #check if config folder exists, otherwise create it
-    [ -d "$configdir" ] || mkdir -p "$configdir"
+    if [ ! -d "$configdir" ]; then
+        mkdir -p "$configdir"
+        cache_tldr
+    fi
 
     [ ! -f $index ] && update_index
     auto_update_index
@@ -49,90 +53,133 @@ auto_update_index() {
     recent "$index" || update_index
 }
 
+style_for() {
+    style=""
+    # sanitize user input, only lowercase and spaces are allowed
+    for i in $(printf %s "$*" | tr -cd '[a-z] '); do
+        eval t=\$$i
+        style="${style}$t"
+    done
+    printf %s "$style"
+}
+
 # function contents via http://mywiki.wooledge.org/BashFAQ/037
 init_term_cmds() {
-    # only set if we're on an interactive session
-    [[ -t 2 ]] && {
+    true && {
         reset=$(    tput sgr0   || tput me      ) # Reset cursor
         bold=$(     tput bold   || tput md      ) # Start bold
-        under=$(    tput smul   || tput us      ) # Start underline
+        underline=$(tput smul   || tput us      ) # Start underline
         italic=$(   tput sitm   || tput ZH      ) # Start italic
         eitalic=$(  tput ritm   || tput ZH      ) # End italic
         default=$(  tput op                     )
-        back=$'\b'
+        back=$(     printf '\b' )
 
-        [[ $TERM != *-m ]] && {
-            black=$(    tput setaf 0 || tput AF 0    )
-            red=$(      tput setaf 1 || tput AF 1    )
-            green=$(    tput setaf 2 || tput AF 2    )
-            yellow=$(   tput setaf 3 || tput AF 3    )
-            blue=$(     tput setaf 4 || tput AF 4    )
-            magenta=$(  tput setaf 5 || tput AF 5    )
-            cyan=$(     tput setaf 6 || tput AF 6    )
-            white=$(    tput setaf 7 || tput AF 7    )
+        case "$TERM" in
+            *-m) ;;
+            *)
+                black=$(    tput setaf 0 || tput AF 0    )
+                red=$(      tput setaf 1 || tput AF 1    )
+                green=$(    tput setaf 2 || tput AF 2    )
+                yellow=$(   tput setaf 3 || tput AF 3    )
+                blue=$(     tput setaf 4 || tput AF 4    )
+                magenta=$(  tput setaf 5 || tput AF 5    )
+                cyan=$(     tput setaf 6 || tput AF 6    )
+                white=$(    tput setaf 7 || tput AF 7    )
 
-            onblue=$(   tput setab 4 || tput AB 4    )
-            ongrey=$(   tput setab 7 || tput AB 7    )
-        }
-    } 2>/dev/null ||:
+                onblue=$(   tput setab 4 || tput AB 4    )
+                ongrey=$(   tput setab 7 || tput AB 7    )
+                ;;
+        esac
+    } 2>/dev/null
 
     # osx's termcap doesn't have italics. The below adds support for iTerm2
     # and is harmless on Terminal.app
     [ "$(get_platform)" = "osx" ] && {
-        italic=$(echo -e "\033[3m")
-        eitalic=$(echo -e "\033[23m")
+        italic=$(printf "\033[3m")
+        eitalic=$(printf "\033[23m")
     }
+
+    # custom styling if set in environment variables
+    sheader=$(style_for ${TLDR_HEADER:-red})
+    squote=$(style_for ${TLDR_QUOTE:-underline})
+    sdescription=$(style_for ${TLDR_DESCRIPTION:-reset})
+    scode=$(style_for ${TLDR_CODE:-bold})
+    sparam=$(style_for ${TLDR_PARAM:-italic})
+    eparam=$(style_for ${TLDR_EPARAM:-eitalic})
 }
 
 heading() {
-    local line="$*"
-    echo "$bold$red${line:2}$reset"
+    printf "%s\n" "${sheader}${*#??}$reset"
 }
 
 quotation() {
-    local line="$*"
-    echo "$under${line:2}$reset"
+    echo "${squote}${*#??}$reset"
 }
 
 list_item() {
-    local line="$*"
-    echo "$line$reset"
+    echo "${sdescription}$*$reset"
+}
+
+style_params() {
+    printf %s "$*" | sed "s/{{/${sparam}/g;s/}}/${eparam}/g"
 }
 
 code() {
-    local line="$*"
-    # I'm sure there's a better way to strip the first and last characters.
-    line="${line:1}"
-    line="${line%\`}"
-    # convert {{variable}} to italics
-    line=${line//\{\{/$italic}
-    line=${line//\}\}/$eitalic}
-
-    echo "$bold$line$reset"
+    # take everything between two backticks, capture it, surround it with styling
+    printf "%s\n" "$*" | sed "s/\`\([^\`]*\)\`/  ${scode}\1${reset}/g"
 }
 
 text() {
-    local line="$*"
-    echo "$line"
+    echo "$*"
+}
+
+contains() {
+    test "${1#*$2}" != "$1"
+}
+
+trim() {
+    var="$*"
+    spaces=${var##*[! ]}
+    var=${var%"$spaces"}
+    spaces=${var%%[! ]*}
+    var=${var#"$spaces"}
+    printf %s "$var"
 }
 
 # an idiot-level recognition of tldr's markdown. Needs improvement, or
 # subcontracting out to a markdown -> ANSI formatting command
 display_tldr() {
+    last_token=''
+    page="$1"
+    page=$(style_params "$page")
+
     # read one line at a time, don't strip whitespace ('IFS='), and process
     # last line even if it doesn't have a newline at the end
-    while IFS= read -r line || [[ -n "$line" ]]; do
-        start=${line:0:1}           # get the first character
-        case "$start" in
-            '#') heading "$line"
+    printf %s "$page" | while IFS= read -r line || [ -n "$line" ]; do
+        # omit empty lines after list items
+        trimmed=$(trim "$line")
+        [ -z "$trimmed" ] && [ "$last_token" = "list_item" ] && continue
+
+        case "$line" in
+            \#*)
+                heading "$line"
+                last_token="heading"
                 ;;
-            '>') quotation "$line"
+            \>*)
+                quotation "$line"
+                last_token="quotation"
                 ;;
-            '-') list_item "$line"
+            -*)
+                list_item "$line"
+                last_token="list_item"
                 ;;
-            '`') code "$line"
+            \`*)
+                code "$line"
+                last_token="code"
                 ;;
-            *) text "$line"
+            *)
+                text "$line"
+                last_token="text"
                 ;;
         esac
     done
@@ -140,65 +187,82 @@ display_tldr() {
 
 # convert the local platorm name to tldr's version
 get_platform() {
-    case `uname -s` in
-        Darwin) echo "osx"    ;;
-        Linux)  echo "linux"  ;;
-        SunOS)  echo "sunos"  ;;
-        *)      echo "common" ;;
+    case $(uname -s) in
+        Darwin)                 echo "osx"    ;;
+        Linux)                  echo "linux"  ;;
+        SunOS)                  echo "sunos"  ;;
+        CYGWIN*|MINGW32*|MSYS*) echo "windows" ;;
+        *)                      echo "common" ;;
     esac
 }
 
 # extract the platform key from index.json, return preferred subpath to tldrpage
 path_for_cmd() {
-    local desc=$(tr '{' '\n' < $index | grep "\"name\":\"$1\"")
-    # results in, eg, "name":"netstat","platform":["linux","osx"]},
+    override="$configdir/local/$1.md"
+    if [ -f "$override" ]; then
+        echo "local/$1.md"
+        return
+    fi
 
-    [ -z "$desc" ] && return
+    # results in, eg, "name":"netstat","platform":["linux","osx"]},
+    desc=$(tr '{' '\n' < $index | grep "\"name\":\"$1\"")
+    [ -z "$desc" ] && echo "-- not found --" && return
 
     # use the platform specific version of the tldr first
-    if [[ $desc =~ \"$platform\" ]]; then
+    if contains $desc "$platform"; then
         echo "$platform/$1.md"
-    elif [[ $desc =~ \"common\" ]]; then
+    elif contains $desc "common"; then
         echo "common/$1.md"
     else
         # take the first one so we can show something, but warn the user
-        local p=$(echo "$desc" | cut -d '"' -f 8)
+        p=$(echo "$desc" | cut -d '"' -f 8)
         >&2 echo -e "${red}tldr page $1 not found in $platform or common, using page from platform $p instead$reset\n"
         echo "$p/$1.md"
     fi
 }
 
+# cache a local copy of the tldrpage
+cache_tldr() {
+    contains "$(tar --version | head -n 1)" bsdtar || taropt='--wildcards --overwrite'
+    curl -sfL https://github.com/tldr-pages/tldr/tarball/master \
+    | tar xzf - --strip-components=2 -C "$configdir" ${taropt-} '*/pages/'
+    update_index
+}
+
 # return the local cached copy of the tldrpage, or retrieve and cache from github
 get_tldr() {
-    local p="$(path_for_cmd $1)"
+    p=$(path_for_cmd "$1")
     cached="$configdir/$p"
     recent "$cached" || {
-        mkdir -p $(dirname $cached)
+        mkdir -p $(dirname "$cached")
         curl -sf -o "$cached" "$base_url/$p"
     }
     # if the curl failed for some reason, keep cat from whinging
     cat "$cached" 2>/dev/null
 }
 
+fetch_tldr() {
+    curl -sf "https://raw.githubusercontent.com/tldr-pages/tldr/master/pages/{$platform,common}/$1.md"
+}
 
 config
 
 usage() {
-    cmd=$(basename $0)
+    cmd=$(basename "$0")
     cat <<EOF
 USAGE: $cmd [options] <command>
 
 [options]
-    -l, --list:      show all available pages
-    -p, --platform:  show page from specific platform rather than autodetecting
-    -u, --update:    update, force retrieving latest copies of locally cached files
-    -h, -?, --help:  this help overview
+    -l, --list:       show all available pages
+    -p, --platform:   show page from specific platform rather than autodetecting
+    -u, -c, --update: update, force retrieving latest copies of locally cached files
+    -h, -?, --help:   this help overview
 
 <command>
     Show examples for this command
 
 The client caches a copy of all pages and the index locally under
-$configdir. By default, the cached copies will expire in $cache_days days.
+$configdir . By default, the cached copies will expire in $cache_days days.
 
 EOF
 exit 0
@@ -212,35 +276,43 @@ do
             tr '{' '\n' < "$configdir/index.json" | cut -d '"' -f4 | column
             exit 0
             ;;
-        -u|--update)
-            force_update=yes
-            update_index
-            ;;
-        -h|-\?|--help)
-            usage
+        -n)
+            TLDR_CACHE=no
             ;;
         -p|--platform)
             shift
             platform=$1
             ;;
-        -*)
+        -u|-c|--cache|--update)
+            cache_tldr
+            exit 0
+            ;;
+        -h|-\?|--help-*)
             usage
             ;;
         *)
-            page=${1:-''}
+            # there are pages with hypens in them, such as git-tag. The below converts
+            # `tldr git tag` to the hyphenated version
+            hyphenated=$(printf %s "$*" | tr ' ' '-')
+            page=${hyphenated:-''}
+            break
             ;;
     esac
     shift
 done
 
-[ -z ${page:-} ] && usage
+[ -z "${page:-}" ] && usage
 
-tldr="$(get_tldr $page)"
+if [ "${TLDR_CACHE-unset}" = "no" ]; then
+    tldr=$(fetch_tldr "$page")
+else
+    tldr=$(get_tldr "$page")
+fi
 
 if [ -z "$tldr" ]; then
     echo "tldr page for command $page not found"
     exit 1
 fi
 
-display_tldr <<< "$tldr"
+display_tldr "$tldr"
 echo
